version: '3.1'

services:
  
  mongo:
    image: mongo:latest
    container_name: wizard_mongo_test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${WIZARD_TEST_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${WIZARD_TEST_MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: wizard_test
    volumes:
      - ./init_mongo/init-mongo-test.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodata:/data/db
    ports:
      - ${WIZARD_TEST_MONGODB_PORT}:27017
  
  wizard_backend:
    container_name: wizard_backend_test
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${WIZARD_TEST_TOMCAT_PORT}:8080
    expose:
      - 8080
    environment:
      WIZARD_MONGODB_HOST: wizard_mongo_test
      WIZARD_MONGODB_PORT: 27017
      WIZARD_MONGODB_USERNAME: ${WIZARD_TEST_MONGODB_USERNAME}
      WIZARD_MONGODB_PASSWORD: ${WIZARD_TEST_MONGODB_PASSWORD}
      WIZARD_MONGODB_DATABASE: wizard_test
      WIZARD_BACKEND_URL: wizard_backend_test
      WIZARD_BACKEND_PORT: ${WIZARD_TEST_TOMCAT_PORT}
      WIZARD_BACKEND_PROTOCOL: http
      ANALYSIS_PROTOCOL: http
      ANALYSIS_URL: analysis-backend-test:80

  analysis:
    env_file:
      - .analysis_test.env
    image: docker.pkg.github.com/histographer/analysis-rest-api/analysis-rest-api:latest
    container_name: analysis-backend-test
    restart: always
    expose:
      - 80

volumes:
  mongodata:
