version: '3.1'

services:
  
  mongo:
    env_file:
      - .env
    container_name: ${DEV_WIZARD_MONGO_CONTAINER_NAME}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.init_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEV_WIZARD_MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DEV_WIZARD_MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: wizard_dev
    volumes:
      - mongodevdata:/data/db
    ports:
      - ${DEV_WIZARD_MONGODB_PORT}:27017
  
  wizard_backend:
    env_file:
      - .env
    container_name: ${DEV_WIZARD_BACKEND_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${DEV_WIZARD_TOMCAT_PORT}:8080
    environment:
      WIZARD_MONGODB_HOST: ${DEV_WIZARD_MONGO_CONTAINER_NAME}
      WIZARD_MONGODB_PORT: 27017
      WIZARD_MONGODB_USERNAME: dev_user
      WIZARD_MONGODB_PASSWORD: dev_password
      WIZARD_MONGODB_DATABASE: wizard_dev

  wizard-mongo-express:
    env_file:
      - .env
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DEV_WIZARD_MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DEV_WIZARD_MONGODB_ROOT_PASSWORD}

volumes:
  mongodevdata:
